baseURL = "https://g1314047.github.io/"
languageCode = "zh-cn"
title = "我的朋友圈"
theme = "Amigo"

[params]
  username = "G.Ark"
  avatar = "/images/avatar.jpg"
  description = "一句话简介"
  cover = "/images/header.png"

  # 评论模式
  commentMode = "none"

  # Artalk 配置
  artalkServer = ""
  artalkSite = ""

  enableDanmaku = true